/* this file is automatically generated */
/* Do not edit                          */

#if defined _WRS_AUTOCONF_INCLUDED || defined AUTOCONF_INCLUDED
#else
#include "autoconf.h"
#endif

#ifndef __vsbConfig_INCLUDED
#define __vsbConfig_INCLUDED

/* this is a temporary wrapper 
 * defined to ease transition to 
 * new coding convention
 *
 * PLEASE DO NOT USE THE VARIABLE
 * _WRS_VX_SMP
 * IN SOURCE CODE
 * PLEASE USE
 * _WRS_CONFIG_SMP
 * INSTEAD
 */
#ifdef _WRS_CONFIG_SMP
#ifndef _WRS_VX_SMP
#define _WRS_VX_SMP _WRS_CONFIG_SMP
#endif /* _WRS_VX_SMP */
#endif /* _WRS_CONFIG_SMP */

/* this is a temporary wrapper 
 * defined to ease transition to 
 * new coding convention
 *
 * PLEASE DO NOT USE THE VARIABLE
 * WV_INSTRUMENTATION
 * IN SOURCE CODE
 * PLEASE USE
 * _WRS_CONFIG_SV_INSTRUMENTATION
 * INSTEAD
 */
#if !defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE) && !defined(_POSIX_AEP_RT_CONTROLLER_C_SOURCE)
#ifdef _WRS_CONFIG_SV_INSTRUMENTATION
#ifndef WV_INSTRUMENTATION
#define WV_INSTRUMENTATION _WRS_CONFIG_SV_INSTRUMENTATION
#endif /* WV_INSTRUMENTATION */
#endif /* _WRS_CONFIG_SV_INSTRUMENTATION */
#endif /* _POSIX_xxx_SOURCE */

#endif
