proc scn81_mos

; ;  ESTIMATOR PARAMETER TABLE UPDATES ; ;
Parameters_csc_est_state_est.emp_mass_fillfrac_100 = 217.43
Parameters_csc_est_state_est.emp_mass_fillfrac_0 = 178.72

Parameters_csc_est_state_est.kfl_topocentric_latitude =   28.635925
Parameters_csc_est_state_est.kfl_topocentric_longitude = -80.708611
Parameters_csc_est_state_est.kfl_alt_wrt_meanrad = 9.056

Parameters_csc_est_state_est.esf_takeoff_accel_limit = 1.01;


; for takeoff, hover, translate, landing
;Parameters_csc_gdn_guidance.csc_gdn_pwpf_off_vertical_limit = 10.0

; Set for takeoff
Parameters_csc_gdn_guidance.tlt_terminal_vertical_vel_zero_mean_bias = 0.000

Parameters_csc_gdn_guidance.arg_roll_inertial_target_vector[0] = -0.358685192122062;
Parameters_csc_gdn_guidance.arg_roll_inertial_target_vector[1] =  0.313997724443385;
Parameters_csc_gdn_guidance.arg_roll_inertial_target_vector[2] =  0.87906220598814;
Parameters_csc_gdn_guidance.arg_roll_body_pointing_vector[0] = 0;
Parameters_csc_gdn_guidance.arg_roll_body_pointing_vector[1] = 1;
Parameters_csc_gdn_guidance.arg_roll_body_pointing_vector[2] = 0;

; Force monoprop coarse thrusters for use at all altitudes for throw study
Parameters_csc_gdn_guidance.lac_monoprop_coarse_transition_alt = 10e6;

Parameters_csc_gdn_guidance.tlt_off_vertical_limit = 2.0

Parameters_csc_gdn_guidance.gal_grav_surface_topo = 1.6;

Parameters_csc_cnt_attitude_control.cac_acs_time_gain_x = 40.0;
Parameters_csc_cnt_attitude_control.cac_acs_time_gain_y = 40.0;
Parameters_csc_cnt_attitude_control.cac_acs_time_gain_z = 40.0;
Parameters_csc_cnt_attitude_control.cac_acs_minimum_coarse_thruster_ontime =30; % milliseconds

Parameters_csc_cnt_attitude_control.cac_rotx_deadband_minus = 0.5*pi/180;
Parameters_csc_cnt_attitude_control.cac_rotx_deadband = 0.5*pi/180;

Parameters_csc_cnt_attitude_control.cac_roty_deadband_minus = 0.5*pi/180;
Parameters_csc_cnt_attitude_control.cac_roty_deadband = 0.5*pi/180;

Parameters_csc_cnt_attitude_control.cac_rotz_deadband_minus = 0.5*pi/180;
Parameters_csc_cnt_attitude_control.cac_rotz_deadband = 0.5*pi/180;

Parameters_csc_cnt_attitude_control.cac_alpha_gain_coarse_only = 1.0

Parameters_csc_gdn_guidance.gdn_altitude_transition_free_drift_landing = -10000;
Parameters_csc_gdn_guidance.gdn_altitude_transition_free_drift_takeoff = -10000;

Parameters_csc_lc_wsim_limit_check.lc_wdt_filename = "lc_def_wdt";
Parameters_csc_lc_wsim_limit_check.lc_adt_filename = "lc_def_adt";
