proc scn91_sim

;----Scenario Time: May 1, 2014 12:00:00 takeoff time
Parameters_csc_sim.ini_year = 2014
Parameters_csc_sim.ini_doy = 352
Parameters_csc_sim.ini_hour = 15
Parameters_csc_sim.ini_minute = 0
Parameters_csc_sim.ini_seconds = 0

; Earth Centered J2000 Initial Conditions
;Propagation from time = 0.0
Parameters_csc_sim.ini_position_v[0] = -3492160.901819470
Parameters_csc_sim.ini_position_v[1] = -4380701.699140448
Parameters_csc_sim.ini_position_v[2] =  3038551.815999415

; Initial Velocity Earth Centered J2000 (m/s)
Parameters_csc_sim.ini_velocity_v[0] =  319.445806028
Parameters_csc_sim.ini_velocity_v[1] =  -254.652389200
Parameters_csc_sim.ini_velocity_v[2] =  0.0

; define landing site lat/long/alt
Parameters_csc_sim.ini_topocentric_latitude =  28.635925
Parameters_csc_sim.ini_topocentric_longitude = -80.708611
Parameters_csc_sim.ini_alt_wrt_meanrad = 9.056;

; define euler angles for initial attitude (rad)
Parameters_csc_sim.ini_rotx = 0
Parameters_csc_sim.ini_roty = 0
Parameters_csc_sim.ini_rotz = 0

; Initial spacecraft body rate (rad/sec)
Parameters_csc_sim.ini_rate_v[0] = 0
Parameters_csc_sim.ini_rate_v[1] = 0
Parameters_csc_sim.ini_rate_v[2] = 0

; lander initial mass (kg)
Parameters_csc_sim.mpl_mass_dry         = 178.72
Parameters_csc_sim.mpl_htp_mass_initial = 25.0
Parameters_csc_sim.mpl_gn2_mass_initial = 9.36

Parameters_csc_sim.tpl_coarse_acs_thrust_to_isp[0,1] = 140
Parameters_csc_sim.tpl_coarse_acs_thrust_to_isp[1,1] = 140

; EGC feedforward torque computation
csc_gdn_prep_main_thruster_position = tfl_thruster_egc_position;
csc_gdn_prep_main_thruster_orientation = tfl_thruster_egc_orientation;

; don't use moon harmonics on the earth
Parameters_csc_sim.gsh_sph_harm_order = 0;

endproc
