%% enum_ap_state.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_ap_state
%

classdef enum_ap_state < uint8
    enumeration
        disabled             (0)
        passive              (1)
        active               (2)
    end
end