%% enum_thruster_id.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_thruster_id
%

classdef enum_thruster_id < uint8
    enumeration
        coarse1              (1)
        coarse2              (2)
        coarse3              (3)
        coarse4              (4)
        coarse5              (5)
        coarse6              (6)
        coarse7              (7)
        coarse8              (8)
        coarse9              (9)
        coarse10             (10)
        coarse11             (11)
        coarse12             (12)
        fine1                (13)
        fine2                (14)
        fine3                (15)
        fine4                (16)
        fine5                (17)
        fine6                (18)
        fine7                (19)
        fine8                (20)
        fine9                (21)
        fine10               (22)
        fine11               (23)
        fine12               (24)
    end
end