%% enum_evs_evnt_enbl_mask_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_evs_evnt_enbl_mask_type
%

classdef enum_evs_evnt_enbl_mask_type < uint8
    enumeration
        Debug                (1)
        Informational        (2)
        Error                (4)
        Critical             (8)
    end
end