%% enum_sc_ats_state.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_sc_ats_state
%

classdef enum_sc_ats_state < uint8
    enumeration
        ats_idle             (2)
        ats_executing        (5)
    end
end