%% enum_time_clock_state_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_time_clock_state_type
%

classdef enum_time_clock_state_type < int16
    enumeration
        invalid              (-1)
        valid                (0)
        flywheel             (1)
    end
end