%% enum_time_tone_source_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_time_tone_source_type
%

classdef enum_time_tone_source_type < int16
    enumeration
        primary              (1)
        redundant            (2)
    end
end