%% enum_evs_log_mode_mask_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_evs_log_mode_mask_type
%

classdef enum_evs_log_mode_mask_type < uint8
    enumeration
        overwrite            (0)
        discard              (1)
    end
end