%% enum_vcids.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_vcids
%

classdef enum_vcids < uint8
    enumeration
        VC0                  (0)
        VC1                  (1)
        VC2                  (2)
        VC8                  (8)
        VC63                 (63)
    end
end