%% enum_CFE_SB_QosEnum_t.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_CFE_SB_QosEnum_t
%

classdef enum_CFE_SB_QosEnum_t < uint8
    enumeration
        LOW                  (0)
        HIGH                 (1)
    end
end