%% enum_tbl_active_buff_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_tbl_active_buff_type
%

classdef enum_tbl_active_buff_type < uint16
    enumeration
        inactive             (0)
        active               (1)
    end
end