%% enum_boolean.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_boolean
%

classdef enum_boolean < uint8
    enumeration
        false                (0)
        true                 (1)
    end
end