%% enum_submode.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_submode
%

classdef enum_submode < uint8
    enumeration
        none                 (1)
        active               (2)
        coast                (3)
        landing_hold         (4)
        landing_targeting    (5)
        landing_terminal     (6)
    end
end