%% enum_evs_evnt_format_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_evs_evnt_format_type
%

classdef enum_evs_evnt_format_type < uint8
    enumeration
        short                (0)
        long                 (1)
    end
end