%% enum_mtv_press_valve_names.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_mtv_press_valve_names
%

classdef enum_mtv_press_valve_names < uint8
    enumeration
        htp_tank_pressurant  (1)
        htp_tank_pressurant_vent (2)
        htp_main_engine_feed (3)
        htp_main_engine_purge (4)
    end
end