%% enum_burn_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_burn_type
%

classdef enum_burn_type < uint8
    enumeration
        inertial             (1)
        gravity_turn         (2)
        vnc                  (3)
        peg                  (4)
    end
end