%% enum_lidar_model_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_burn_type
%

classdef ldir_model_type < uint8
    enumeration
        flir_15k             (1)
        flir_2k              (2)
        flir_100m            (3)
    end
end