%% enum_evs_event_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_evs_event_type
%

classdef enum_evs_event_type < uint16
    enumeration
        DEBUG                (1)
        INFO                 (2)
        ERROR                (3)
        CRITICAL             (4)
    end
end