%% enum_evs_port_mask_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_evs_port_mask_type
%

classdef enum_evs_port_mask_type < uint8
    enumeration
        port_one             (1)
        port_two             (2)
        port_three           (4)
        port_four            (8)
    end
end