%% enum_landed_state.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_landed_state
%

classdef enum_landed_state < uint8
    enumeration
        landed               (1)
        flying               (0)
    end
end