%% enum_time_clock_source_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_time_clock_source_type
%

classdef enum_time_clock_source_type < int16
    enumeration
        internal             (1)
        external             (2)
    end
end