%% enum_mode.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_mode
%

classdef enum_mode < uint8
    enumeration
        startup              (1)
        safe                 (2)
        pointing             (3)
        deltav               (4)
        deorbit              (5)
        braking              (6)
        landing              (7)
        surface              (8)
        safesurface          (9)
    end
end