%% enum_lidar_model_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_lidar_model_type
%

classdef enum_lidar_model_type < uint8
    enumeration
        flr_100m             (1)
        flr_15k              (2)
    end
end