%% enum_thruster_type.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_thruster_type
%

classdef enum_thruster_type < uint8
    enumeration
        coarse               (1)
        fine                 (2)
        mono                 (3)
        biprop               (4)
        coarse_fine          (5)
    end
end
