%% enum_valve_state.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_valve_state
%

classdef enum_valve_state < uint8
    enumeration
        open                 (1)
        close                (0)
    end
end