%% enum_reference_frame.m
% AUTOGENERATED -- DO NOT EDIT
%
% Definition for enumerated type enum_reference_frame
%

classdef enum_reference_frame < uint8
    enumeration
        inertial             (1)
        topocentric          (2)
    end
end