%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright 2010 - 2015 Moon Express, Inc.
% All Rights Reserved.
%
% PROPRIETARY DATA NOTICE:
% The data herein include Proprietary Data and are restricted under the
% Data Rights provisions of Lunar CATALYST Space Act Agreement
% No. SAAM ID# 18251 and Reimbursable Space Act Agreement No.SAA2-402930.
% All information contained herein is and remains proprietary to and the
% property of Moon Express, Inc. Dissemination of this information or
% reproduction of this material is strictly forbidden unless prior
% written permission is obtained from Moon Express, Inc.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

currentpwd = pwd;
[pathstr, name, ext] = fileparts(which('mex_sfun_hmg.m'));
cd(pathstr);
mex(['-I' fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','include')],'sfun_hmg.cpp',...
    'hmg_obj.cpp',...
    'sfun_hmg_wrapper.cpp',...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','algorithm.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','alloc.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','arithm.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','array.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','calibration.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','color.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','convert.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','copy.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','datastructs.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','descriptors.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','detectors.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','drawing.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','fast.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','fast_score.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','filter.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','fundam.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','histogram.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','imgwarp.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','keypoint.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','lapack.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','matchers.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','mathfuncs.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','matmul.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','matop.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','matrix.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','modelest.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','orb.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','parallel.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','pyramids.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','smooth.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','stat.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','system.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','thresh.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','undistort.cpp'),...
    fullfile(getenv('NIMBUS_ROOT'),'externals','minopencv','utils.cpp')...
    )
cd(currentpwd);
